#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Run MiMo-CodeHarness v0.3.1 on multiple real repository case studies.

This wrapper is designed for portfolio/research evidence generation. It can:
1. read a JSON case-study config;
2. optionally clone missing GitHub repositories;
3. run MiMo-CodeHarness on each repository;
4. generate a combined case-study index, CSV summary, and dashboard links.

Important safety notes:
- It never stores API keys. Use environment variables such as MIMO_API_KEY.
- Patches are applied only inside copied worktrees created by the underlying harness.
- Without --execute, all model calls use dry-run/mock mode.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from run_mimo_codeharness_v02 import run_harness  # noqa: E402


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    ensure_dir(path.parent)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    ensure_dir(path.parent)
    keys: List[str] = []
    for row in rows:
        for key in row.keys():
            if key not in keys:
                keys.append(key)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def is_placeholder_url(url: str) -> bool:
    lowered = (url or "").lower()
    return not url or "your_username" in lowered or "example.com" in lowered


def resolve_path(path_text: str) -> Path:
    path = Path(path_text).expanduser()
    if not path.is_absolute():
        path = ROOT / path
    return path.resolve()


def run_cmd(cmd: List[str], cwd: Optional[Path] = None, timeout: int = 600) -> Dict[str, Any]:
    start = time.perf_counter()
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd) if cwd else None,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
        )
        return {
            "status": "ok" if proc.returncode == 0 else "failed",
            "returncode": proc.returncode,
            "time_seconds": round(time.perf_counter() - start, 3),
            "stdout": proc.stdout[-4000:],
            "stderr": proc.stderr[-4000:],
        }
    except Exception as exc:
        return {
            "status": "error",
            "returncode": None,
            "time_seconds": round(time.perf_counter() - start, 3),
            "stdout": "",
            "stderr": f"{type(exc).__name__}: {exc}",
        }


def prepare_repo(case: Dict[str, Any], clone_missing: bool) -> Dict[str, Any]:
    path = resolve_path(str(case.get("path", "")))
    git_url = str(case.get("git_url", "")).strip()
    result: Dict[str, Any] = {
        "case_name": case.get("name", path.name),
        "repo_path": str(path),
        "git_url": git_url,
        "prepared": False,
        "prepare_status": "missing",
        "prepare_note": "",
    }

    if path.exists():
        result.update({"prepared": True, "prepare_status": "exists", "prepare_note": "Repository path already exists."})
        return result

    if not clone_missing:
        result["prepare_note"] = "Path does not exist and --clone-missing was not set."
        return result

    if is_placeholder_url(git_url):
        result["prepare_note"] = "Path missing and git_url is empty or still a placeholder."
        return result

    ensure_dir(path.parent)
    clone = run_cmd(["git", "clone", "--depth", "1", git_url, str(path)], cwd=ROOT, timeout=900)
    result["clone_result"] = clone
    if clone["status"] == "ok" and path.exists():
        result.update({"prepared": True, "prepare_status": "cloned", "prepare_note": "Repository cloned successfully."})
    else:
        result.update({"prepared": False, "prepare_status": "clone_failed", "prepare_note": clone.get("stderr", "")[:1000]})
    return result


def markdown_link(path: str, label: str) -> str:
    return f"[{label}]({Path(path).as_posix()})" if path else ""


def generate_index(out_dir: Path, rows: List[Dict[str, Any]], execute: bool) -> Path:
    lines: List[str] = []
    lines.append("# MiMo-CodeHarness Real Repository Case Study Index")
    lines.append("")
    lines.append("This index summarizes the real-repository runs generated by `src/run_real_repo_case_studies.py`.")
    lines.append("")
    lines.append(f"- Mode: {'real MiMo/API execution' if execute else 'dry-run/mock execution'}")
    lines.append(f"- Case count: {len(rows)}")
    lines.append("")
    lines.append("| Case | Type | Status | Files | Tasks | Avg Score | Token Est. | Key Outputs |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---|")
    for row in rows:
        outputs = []
        if row.get("dashboard"):
            outputs.append(markdown_link(row["dashboard"], "dashboard"))
        if row.get("technical_report"):
            outputs.append(markdown_link(row["technical_report"], "report"))
        if row.get("paper_draft"):
            outputs.append(markdown_link(row["paper_draft"], "paper draft"))
        lines.append(
            "| {case_name} | {case_type} | {status} | {files} | {tasks} | {avg_score} | {tokens} | {outputs} |".format(
                case_name=row.get("case_name", ""),
                case_type=row.get("case_type", ""),
                status=row.get("status", ""),
                files=row.get("file_count", ""),
                tasks=row.get("task_count", ""),
                avg_score=row.get("overall_avg_score", ""),
                tokens=row.get("total_tokens_est", ""),
                outputs="; ".join(outputs),
            )
        )
    lines.append("")
    lines.append("## Recommended portfolio narrative")
    lines.append("")
    lines.append(
        "MiMo-CodeHarness evaluates repository-level code-agent ability across real projects by scanning repositories, "
        "constructing dependency context, generating tasks, executing model agents, checking patches/builds, recording token usage, "
        "and generating reproducible reports."
    )
    path = out_dir / "REAL_REPO_CASE_STUDY_INDEX.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description="Run MiMo-CodeHarness v0.2 on multiple real repositories.")
    parser.add_argument("--cases", default=str(ROOT / "config" / "real_repo_cases.example.json"), help="Case-study JSON config")
    parser.add_argument("--config", default=str(ROOT / "config" / "api_models_mimo.json"), help="Model config JSON")
    parser.add_argument("--suite-name", default="real_repo_case_studies", help="Output suite name")
    parser.add_argument("--execute", action="store_true", help="Call real APIs. Without this flag, dry-run/mock mode is used.")
    parser.add_argument("--clone-missing", action="store_true", help="Clone missing repositories when git_url is provided.")
    parser.add_argument("--apply-patches", action="store_true", help="Apply patches inside isolated copied worktrees after validation.")
    parser.add_argument("--run-build-tests", action="store_true", help="Run detected external build/test commands; syntax checks always run.")
    parser.add_argument("--llm-review", default="", help="Optional JSON/CSV LLM judge scores passed to scoring v0.3")
    parser.add_argument("--human-review", default="", help="Optional JSON/CSV human review scores passed to scoring v0.3")
    parser.add_argument("--human-rubric", default="", help="Optional JSON human rubric file passed to scoring v0.3")
    parser.add_argument("--limit-cases", type=int, default=0, help="Run only the first N prepared cases. 0 means all.")
    parser.add_argument("--default-limit-tasks", type=int, default=6, help="Default task limit per case")
    parser.add_argument("--default-max-files", type=int, default=800, help="Default max scanned files per case")
    args = parser.parse_args()

    cases_cfg = load_json(resolve_path(args.cases) if not Path(args.cases).is_absolute() else Path(args.cases))
    cases = cases_cfg.get("cases", [])
    suite_dir = ensure_dir(ROOT / "outputs" / "mimo_codeharness_v02" / args.suite_name)

    rows: List[Dict[str, Any]] = []
    raw_logs: List[Dict[str, Any]] = []
    prepared_count = 0

    for case in cases:
        prep = prepare_repo(case, clone_missing=args.clone_missing)
        case_name = str(case.get("name") or Path(prep["repo_path"]).name)
        case_type = str(case.get("type", "unspecified"))
        row: Dict[str, Any] = {
            "case_name": case_name,
            "case_type": case_type,
            "repo_path": prep["repo_path"],
            "prepare_status": prep["prepare_status"],
            "status": "skipped",
            "note": prep.get("prepare_note", ""),
        }
        raw_logs.append({"case": case, "prepare": prep})

        if not prep["prepared"]:
            rows.append(row)
            continue

        if args.limit_cases and prepared_count >= args.limit_cases:
            row.update({"status": "skipped_by_limit", "note": "Prepared but skipped because --limit-cases was reached."})
            rows.append(row)
            continue

        prepared_count += 1
        limit_tasks = int(case.get("limit_tasks") or args.default_limit_tasks)
        max_files = int(case.get("max_files") or args.default_max_files)
        run_name = f"{args.suite_name}__{case_name}"

        try:
            log = run_harness(
                project=Path(prep["repo_path"]),
                name=run_name,
                config_path=Path(args.config) if Path(args.config).is_absolute() else ROOT / args.config,
                limit_tasks=limit_tasks,
                max_files=max_files,
                execute=args.execute,
                apply_patch_flag=args.apply_patches,
                run_build_tests=args.run_build_tests,
                llm_review_path=args.llm_review,
                human_review_path=args.human_review,
                human_rubric_path=args.human_rubric,
            )
            out = log.get("key_outputs", {})
            repo_summary = log.get("repo_summary", {})
            score_summary = log.get("score_summary", {})
            row.update({
                "status": "ok",
                "file_count": repo_summary.get("file_count", ""),
                "dependency_count": log.get("dependency_summary", {}).get("dependency_count", log.get("dependency_summary", {}).get("edge_count", "")),
                "task_count": log.get("task_count", ""),
                "overall_avg_score": score_summary.get("overall_avg_score", ""),
                "total_tokens_est": score_summary.get("total_tokens_est", ""),
                "dashboard": out.get("dashboard", ""),
                "technical_report": out.get("technical_report", ""),
                "paper_draft": out.get("paper_draft", ""),
                "token_usage": out.get("token_usage", ""),
                "evaluation_scores": out.get("evaluation_scores", ""),
            })
            raw_logs.append({"case_name": case_name, "run_log": log})
        except Exception as exc:  # keep batch running if one repo fails
            row.update({"status": "failed", "note": f"{type(exc).__name__}: {exc}"})
            raw_logs.append({"case_name": case_name, "error": row["note"]})
        rows.append(row)

    write_csv(suite_dir / "case_study_summary.csv", rows)
    write_json(suite_dir / "case_study_raw_logs.json", raw_logs)
    index_path = generate_index(suite_dir, rows, execute=args.execute)

    print(json.dumps({
        "suite_dir": str(suite_dir),
        "index": str(index_path),
        "case_count": len(rows),
        "prepared_count": prepared_count,
        "execute": args.execute,
        "summary_csv": str(suite_dir / "case_study_summary.csv"),
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
